services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  fintonic:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mongo-data:
